_template/prody.html

An additional empty img tag was removed -- Hongchun

remove an empty img tag

---

tutorials/signdy_tutorial/classifications.rst
tutorials/signdy_tutorial/core.rst
tutorials/signdy_tutorial/data.rst
tutorials/signdy_tutorial/intro.rst

applying four spaces indent in the rst files under signdy_tutorial folder, except the intro.rst.

indent fixed in a few rst files

---

tutorials/mech_stiff/sm.rst

Fix spotted by @MollyGravett in prody/prody#786

fixed wrong command for writeDeformProfile

---

_static/js/prodydocs.js
_template/index.html
_template/pharmmaker.html

I made it so it doesn't have a link to nowhere.

 updated pharmmaker reference and removed an outdated comment

---

tutorials/mech_stiff/sm.rst

This should fix https://github.com/prody/ProDy/issues/786

bug fix to mech_stiff tutorial

---

tutorials/perturb_response/calculations.rst

This helps with ProDy issue https://github.com/prody/ProDy/issues/1042

PRS tutorial now mentions other models and matrices

---

tutorials/cryoem_tutorial/em_analysis.rst
tutorials/signdy_tutorial/overview.rst

This is the same as #62 was, but it takes over because of tidying up my branches.

fixes to cryoem and signdy tutorials (#62)

---

tutorials/signdy_tutorial/cath.rst
tutorials/signdy_tutorial/index.rst
tutorials/signdy_tutorial/intro.rst

This should satisfy #63 and https://github.com/prody/ProDy/issues/1124

added CATH tutorial

---

tutorials/enm_analysis/gnm.rst
tutorials/ensemble_analysis/blast.rst
tutorials/ensemble_analysis/dimer.rst
tutorials/ensemble_analysis/xray_calculations.rst
tutorials/ensemble_analysis/xray_plotting.rst
tutorials/prody_tutorial/basics.rst

building fixes

---

_template/workshop.html

Changed files and citations and tidied up with beautify.

updated workshop for 2020

---

conf.py

added cryody and essa to conf.py

added cryody and essa to conf.py

---

conf.py

cryody and essa to conf.py fix

---

_template/index.html

they are tiffs not png. Also antisymmetric needed a hyphen

fixed cryody fig names

---

tutorials/cryoem_tutorial/em_analysis.rst

Also set emd2 back to emd as that might be necessary for comparing using pmap.

removed verbatim in em tutorial

---

tutorials/signdy_tutorial/classifications.rst

Figure and later code lines weren't showing up.

signdy fix

---

_template/index.html
_template/prody.html

cryody improvements

---

tutorials/aanm/calculations.rst

Makes it clearer how to analyse

aanm tutorial improvement

---

tutorials/signdy_tutorial/core.rst
tutorials/signdy_tutorial/overview.rst

I think they should be at the last figure step to make the figure show.

moved @savefig for signdy tutorial

---

tutorials/signdy_tutorial/core.rst
tutorials/signdy_tutorial/overview.rst

extra savefigs

---

tutorials/aanm/calculations.rst
tutorials/signdy_tutorial/overview.rst

1. Made Adaptive ANM callback function work
2. Hopefully fixed SignDy variance bar in overview page

minor fixes

---

tutorials/cryoem_tutorial/index.rst

Now the domain decomp tutorial will show up.

updated index

---

tutorials/prs_tutorial/analysis.rst

This one removes a duplicated line that was spotted when making the other fixes.

another prs tutorial fix

---

_template/prody.html

The ProDy 2.0 paper now has volume, issue and page numbers

updated citation

---

tutorials/structure_analysis/compare.rst

Fixes https://github.com/prody/ProDy/issues/1653

update struct comp tutorial

---

tutorials/clustenmd_tutorial/clustenmd.rst

fixes https://github.com/prody/ProDy/issues/1819

fix and clarify clustenm rmsd arg

---

_template/downloads.html

update Python versions for download/install instructions

---

_template/downloads.html

This is working on http://3.142.54.46/downloads/

updated download install instructions

---

_template/index.html

The old page doesn't exist anymore

update pyparsing link

---

tutorials/insty_tutorial/intro.rst

This is now simpler and includes conda-forge.

update insty intro

---

tutorials/insty_tutorial/ligand.rst

1. Fix indents of some code that wasn't showing up as code
2. Make the code verbatim so it doesn't matter if it doesn't run

Fix Ligand tutorial
